package uk.nhs.prm.repo.ehrtransferservice.database;

public enum TransferState {
    EHR_TRANSFER_STARTED,
    EHR_REQUEST_SENT_TO_GP2GP_MESSENGER,
    EHR_CORE_RECEIVED_BY_EHR_TRANSFER_SERVICE,
    CONTINUE_REQUEST_SENT_TO_GP2GP_MESSENGER,
    LARGE_EHR_RECEIVED_BY_EHR_TRANSFER_SERVICE,
    EHR_SENT_TO_REPOSITORY,
    EHR_TRANSFER_FAILED,
    EHR_TRANSFER_TIMEOUT
}
