format_version: 4
pipelines:
  ehr-transfer-service.audit:
    group: repo-audit
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
    timer:
      spec: 0 0 9 ? * MON,TUE,WED,THU,FRI *
    stages:
      - audit:
          clean_workspace: true
          approval: manual
          jobs:
            dependency_check:
              artifacts:
                - build:
                    source: build/reports
              tabs:
                dependency: reports/dependency-check-report.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
